/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/bin/xcalib -d :0 /usr/share/color/icc/NV156FHM_N61.icm
dunst &
firefox &
alacritty &
nvim-qt &
telegram-desktop &
nautilus &
spotify &
discord --start-minimized &
xrandr --dpi 96 --output DP-0 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-0 --off &
feh --no-fehbg --bg-scale Pictures/wallpaper.jpg &
picom -C &
# slack -u &
# upwork &
exec i3

